#!/usr/bin/env ruby
# coding: utf-8


require 'optparse'
require 'zotica'
include Zenithal


class Executor

  def initialize(args)
    @mode, @options, @paths = nil, {}, []
    parser = OptionParser.new
    parser.on("-o PATH") do |value|
      @options[:output_path] = value
    end
    parser.on("-m NAME") do |value|
      @options[:math_macro_name] = value
    end
    parser.on("-r NAME") do |value|
      @options[:raw_macro_name] = value
    end
    parser.on("-c NAME") do |value|
      @options[:resource_macro_name] = value
    end
    parser.on("-f PATH") do |value|
      @options[:font_path] = value
    end
    parser.on("-z") do
      @mode = nil
    end
    parser.on("-l") do
      @mode = :light
    end
    parser.on("-j") do
      @mode = :script
    end
    parser.on("-s") do
      @mode = :style
    end
    @paths = parser.parse(args)
  end

  def execute
    case @mode
    when :light
      convert(true)
    when :script, :style
      output_resource
    else
      convert(false)
    end
  end

  def convert(only_math = false)
    unless @paths.empty?
      source = File.read(@paths.first)
    else
      source = STDIN.read
    end
    if only_math
      parser = ZoticaSingleParser.new(source)
    else
      parser = ZoticaParser.new(source)
      parser.register_simple_math_macro(@options[:math_macro_name] || "m")
      parser.register_raw_macro(@options[:raw_macro_name] || "raw")
      parser.register_resource_macro(@options[:resource_macro_name] || "math-resource")
    end
    parser.load_font(@options[:font_path])
    document = parser.run
    converter = ZenithalConverter.simple_html(document)
    output = converter.convert
    if @options[:output_path]
      File.write(@options[:output_path], output)
    else
      STDOUT.print(output)
    end
  end

  def output_resource
    case @mode
    when :script
      output = ZoticaBuilder.create_script_string
    when :style
      font_url = @options[:font_path] || "font.otf"
      output = ZoticaBuilder.create_style_string(font_url)
    end
    if @options[:output_path]
      File.write(@options[:output_path], output)
    else
      STDOUT.print(output)
    end
  end
end


executor = Executor.new(ARGV)
executor.execute