#!/usr/bin/env ruby
# coding: utf-8


require 'optparse'
require 'zotica'
include Zenithal


class Executor

  def initialize(args)
    @mode, @options, @paths = nil, {}, []
    parser = OptionParser.new
    parser.on("--create-font") do |value|
      @mode = :create_font
    end
    parser.on("-o PATH") do |value|
      @options[:output_path] = value
    end
    parser.on("-m NAME") do |value|
      @options[:math_macro_name] = value
    end
    parser.on("-r NAME") do |value|
      @options[:raw_macro_name] = value
    end
    parser.on("-s NAME") do |value|
      @options[:resource_macro_name] = value
    end
    parser.on("-f PATH") do |value|
      @options[:font_path] = value
    end
    parser.on("-a ASCENT", Numeric) do |value|
      @options[:ascent] = value.to_f
    end
    parser.on("-d DESCENT", Numeric) do |value|
      @options[:descent] = value.to_f
    end
    @paths = parser.parse(args)
  end

  def execute
    case @mode
    when :create_font
      create_font
    else
      convert
    end
  end

  def convert
    unless @paths.empty?
      source = File.read(@paths.first)
    else
      source = STDIN.read
    end
    parser = ZoticaParser.new(source)
    parser.simple_math_macro_name = @options[:math_macro_name] || "m"
    parser.raw_macro_name = @options[:raw_macro_name] || "raw"
    parser.resource_macro_name = @options[:resource_macro_name] || "math-resource"
    parser.load_font(@options[:font_path])
    document = parser.parse
    converter = ZenithalConverter.simple_html(document)
    output = converter.convert
    if @options[:output_path]
      File.write(@options[:output_path], output)
    else
      STDOUT.print(output)
    end
  end

  def create_font
    metrics = {}
    metrics[:ascent] = @options[:ascent] || 1638
    metrics[:descent] = @options[:descent] || 410
    metrics[:em] = metrics[:ascent] + metrics[:descent]
    output = ZoticaParserMethod.create_font_string(:main, @paths.first, metrics)
    if @options[:output_path]
      File.write(@options[:output_path], output)
    else
      STDOUT.print(output)
    end
  end

end


executor = Executor.new(ARGV)
executor.execute